clc;
close all;
tp=25;
t=1:1/(100*tp):50;
x=exp(-2*pi*(1/tp)*t);
%x=5*sinc(2*pi*(1/tp)*t);
%c=cos(2*pi*(10/tp)*t);
% y=x.*c;
% figure;
% subplot(3,1,1);
% plot(t,x);
% subplot(3,1,2);
% plot(t,c);
% subplot(3,1,3);
% plot(t,y);
figure;
plot(x);
figure;
plot(fft(x));